INSERT INTO TICKETS (AUTHOR, TITLE, STATUS,DESCRIPTION,LAST_EDIT) VALUES
('TEST1','I HATE JIRA','DEVELOPMENT', 'I DONT WORK', SYSDATE),
('TEST2', ' I REALLY HATE JIRA','UAT TESTING', 'I SHOULD WORK BUT DONT',SYSDATE),
('TEST3', 'JIRA WAS DEVELOPED TO ANNOY ME', 'CLOSED', 'I DO WORK',SYSDATE);