INSERT INTO TICKETS (ID, AUTHOR, TITLE, STATUS,DESCRIPTION,LAST_EDITED) VALUES
(1,'TEST1','I HATE JIRA','DEVELOPMENT', 'I DONT WORK', SYSDATE),
(2,'TEST2', ' I REALLY HATE JIRA','UAT_TESTING', 'I SHOULD WORK BUT DONT',SYSDATE),
(3,'TEST3', 'JIRA WAS DEVELOPED TO ANNOY ME', 'CLOSED', 'I DO WORK',SYSDATE);